# Generated by Django 5.2.15 on 2026-06-28 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_alter_car_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('location', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reschedule_count', models.PositiveSmallIntegerField(default=0)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_bookings', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_bookings', to='listings.car')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inspections.inspectionslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionslot',
            index=models.Index(fields=['date', 'is_active'], name='inspections_date_c80ac4_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionslot',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time', 'location'), name='unique_slot_per_date_time_location'),
        ),
        migrations.AddIndex(
            model_name='inspectionbooking',
            index=models.Index(fields=['slot', 'status'], name='inspections_slot_id_7fb760_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('car',), name='one_active_booking_per_car'),
        ),
    ]
