# Generated by Django 5.2.15 on 2026-07-08 04:46

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


def purge_pre_center_slots(apps, schema_editor):
    """Old slots used a free-text location that cannot be mapped to the new
    InspectionCenter FK. Any DB migrating through here loses its legacy
    slot/booking test data by design — without this, the non-null `center`
    AddField below fails on populated tables."""
    InspectionBooking = apps.get_model("inspections", "InspectionBooking")
    InspectionSlot = apps.get_model("inspections", "InspectionSlot")
    InspectionBooking.objects.all().delete()
    InspectionSlot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        ('listings', '0009_car_tracking_id_alter_car_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(purge_pre_center_slots, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CarStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_role', models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('system', 'System')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Status History',
                'verbose_name_plural': 'Car Status Histories',
                'db_table': 'car_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2)),
                ('country_code', models.CharField(default='NG', max_length=3)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=3)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('max_reschedules', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inspection Center',
                'verbose_name_plural': 'Inspection Centers',
                'db_table': 'inspection_centers',
                'ordering': ['company_name', '-created_at', 'country', 'state'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_documents', models.FileField(upload_to='inspection-docs/%Y/%m/')),
                ('receipt_upload', models.FileField(upload_to='inspection-docs/receipts/%Y/%m/')),
                ('custom_duty_status', models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partly_paid', 'Partly Paid'), ('not_available', 'Not Available')], max_length=20)),
                ('receipt_type', models.CharField(choices=[('company', 'Company'), ('other', 'Other'), ('dealership', 'Dealership')], max_length=20)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspection Document',
                'verbose_name_plural': 'Inspection Documents',
                'db_table': 'inspection_documents',
            },
        ),
        migrations.CreateModel(
            name='PhysicalInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('used', 'Used'), ('brand_new', 'Brand New')], max_length=30)),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('car_type', models.CharField(choices=[('foreign_used', 'Foreign Used'), ('brand_new', 'Brand New'), ('local_used', 'Local Used')], max_length=20)),
                ('features', models.JSONField(default=list)),
                ('engine_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=30)),
                ('chassis_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('ac_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('is_flooded', models.BooleanField(default=False)),
                ('has_accident_history', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('needs_clearance', 'Needs Clearance'), ('failed', 'Failed')], max_length=20)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('inspected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Physical Inspection',
                'verbose_name_plural': 'Physical Inspections',
                'db_table': 'physical_inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inspectionslot',
            name='unique_slot_per_date_time_location',
        ),
        migrations.RemoveField(
            model_name='inspectionslot',
            name='location',
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='listings.car'),
        ),
        migrations.AddField(
            model_name='inspectioncenter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionslot',
            name='center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inspections.inspectioncenter'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inspectionslot',
            constraint=models.UniqueConstraint(fields=('date', 'start_time', 'end_time', 'center'), name='unique_slot_per_date_time_center'),
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspections.inspectionbooking'),
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_inspections', to='listings.car'),
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.physicalinspection'),
        ),
        migrations.AddIndex(
            model_name='carstatushistory',
            index=models.Index(fields=['car', 'created_at'], name='car_status__car_id_9c6014_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectioncenter',
            index=models.Index(fields=['is_active'], name='inspection__is_acti_c4f881_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectioncenter',
            index=models.Index(fields=['company_name'], name='inspection__company_1bd5b2_idx'),
        ),
    ]
