# Generated by Django 5.2.15 on 2026-07-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_carstatushistory_inspectioncenter_inspectiondocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstatushistory',
            name='actor_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='actor_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carstatushistory',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
