# Generated by Django 5.2.15 on 2026-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_carstatushistory_actor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatushistory',
            name='actor_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
