# Generated by Django 5.2.15 on 2026-07-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_carstatushistory_actor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbooking',
            name='attendee_type',
            field=models.CharField(choices=[('self', 'Owner attends'), ('representative', 'Representative attends')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='rep_id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='rep_id_type',
            field=models.CharField(blank=True, choices=[('intl_passport', 'International Passport'), ('nin', 'NIN'), ('voters_card', "Voter's Card"), ('drivers_licence', "Driver's Licence")], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='rep_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
