# Generated by Django 5.2.15 on 2026-07-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_assistancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalinspection',
            name='presented_id_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-docs/presented/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='presented_id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='physicalinspection',
            name='presented_id_type',
            field=models.CharField(blank=True, choices=[('intl_passport', 'International Passport'), ('nin', 'NIN'), ('voters_card', "Voter's Card"), ('drivers_licence', "Driver's Licence")], default='', max_length=20),
        ),
    ]
