# Generated by Django 5.2.15 on 2026-07-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_physicalinspection_presented_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalinspection',
            name='presented_attendee',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('representative', 'Declared representative'), ('other', 'Someone else')], default='', max_length=20),
        ),
    ]
