# Generated by Django 5.2.15 on 2026-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_physicalinspection_presented_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalinspection',
            name='presented_attendee',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('representative', 'Declared representative')], default='', max_length=20),
        ),
    ]
