# Generated by Django 5.2.15 on 2026-07-30 17:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_clear_other_presented_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('listing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0750'), max_digits=5)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Setting',
                'verbose_name_plural': 'Fee Settings',
            },
        ),
    ]
