# Generated by Django 5.2.15 on 2026-07-30 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_feesetting'),
        ('listings', '0015_rename_listingfeature_value_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inspectionbooking',
            name='one_active_booking_per_car',
        ),
        migrations.AlterField(
            model_name='inspectionbooking',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inspectionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_payment', 'pending', 'approved'])), fields=('car',), name='one_active_booking_per_car'),
        ),
    ]
