# Generated by Django 5.2.15 on 2026-07-30 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_remove_inspectionbooking_one_active_booking_per_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listing_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('receipt', models.FileField(upload_to='inspection_payments/')),
                ('payment_method', models.CharField(choices=[('transfer', 'Bank Transfer'), ('card', 'Card')], default='transfer', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                ('staff_note', models.CharField(blank=True, default='', max_length=400)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='inspections.inspectionbooking')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
