# Generated by Django 5.2.15 on 2026-08-22 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_inspectionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionEditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('editor_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited')], max_length=10)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_events', to='inspections.physicalinspection')),
            ],
            options={
                'db_table': 'inspection_edit_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
