# Generated by Django 5.2.15 on 2026-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_inspectioneditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstatushistory',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
