# Generated by Django 5.2.15 on 2026-08-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_carstatushistory_changed_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionslot',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='inspections.inspectioncenter'),
        ),
    ]
