# Generated by Django 5.2.15 on 2026-06-11 21:36

import apps.listings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy'), ('both', 'Both')], max_length=10)),
                ('rent_price_per_day', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)')], default='NGN', max_length=3)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('van', 'Van'), ('wagon', 'Wagon'), ('convertible', 'Convertible'), ('minivan', 'Minivan'), ('crossover', 'Crossover')], max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.listings.models.car_image_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.car')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listings.car')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['listing_type', 'status'], name='listings_ca_listing_9319cb_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['owner', 'status'], name='listings_ca_owner_i_c06eea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['state', 'city'], name='listings_ca_state_df54ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('car',), name='one_primary_image_per_car'),
        ),
    ]
