# Generated by Django 5.2.15 on 2026-06-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy'), ('both', 'Both')], max_length=10)),
                ('price_offered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)')], default='NGN', max_length=3)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('owner_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='listings.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='listings.request')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['customer', 'status'], name='listings_re_custome_11b160_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['car', 'status'], name='listings_re_car_id_23d602_idx'),
        ),
    ]
