# Generated by Django 5.2.15 on 2026-06-14 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_request_requeststatusevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('needs_changes', 'Needs Changes'), ('published', 'Published'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'paid', 'active'])), fields=('car', 'customer', 'request_type'), name='unique_active_request_per_customer_car_type'),
        ),
    ]
