# Generated by Django 5.2.15 on 2026-06-14 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_car_admin_note_alter_car_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)')], default='NGN', max_length=3)),
                ('transaction_type', models.CharField(choices=[('rental', 'Rental'), ('purchase', 'Purchase'), ('refund', 'Refund')], max_length=20)),
                ('payment_method', models.CharField(choices=[('manual', 'Manual (Bank Transfer/Cash)'), ('card', 'Card'), ('paystack', 'Paystack'), ('opay', 'Opay'), ('transfer', 'Bank Transfer')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='listings.request')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', 'status'], name='listings_tr_payer_i_917c26_idx'), models.Index(fields=['receiver', 'status'], name='listings_tr_receive_03d129_idx')],
            },
        ),
    ]
