# Generated by Django 5.2.15 on 2026-06-16 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='unique_active_request_per_customer_car_type',
        ),
        migrations.AddField(
            model_name='request',
            name='payment_method_choice',
            field=models.CharField(blank=True, choices=[('transfer', 'Bank Transfer'), ('card', 'Card')], max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('payment_submitted', 'Payment Submitted'), ('paid', 'Paid'), ('active', 'Active'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'payment_submitted', 'paid', 'active'])), fields=('car', 'customer', 'request_type'), name='unique_active_request_per_customer_car_type'),
        ),
    ]
