# Generated by Django 5.2.15 on 2026-06-19 11:13

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_request_unique_active_request_per_customer_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.listings.models.car_image_thumbnail_path),
        ),
    ]
