# Generated by Django 5.2.15 on 2026-06-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_carimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspection_pending', 'Inspection Pending'), ('inspection_approved', 'Inspection Approved'), ('inspection_rejected', 'Inspection Rejected'), ('inspection_no_show', 'Inspection No Show'), ('needs_changes', 'Needs Changes'), ('published', 'Published'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
