# Generated by Django 5.2.15 on 2026-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_car_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="carimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("front", "Front"),
                    ("back", "Back"),
                    ("left_side", "Left Side"),
                    ("right_side", "Right Side"),
                    ("interior", "Interior"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="carimage",
            constraint=models.UniqueConstraint(
                condition=~models.Q(image_type=""),
                fields=("car", "image_type"),
                name="one_image_per_type_per_car",
            ),
        ),
    ]
