# Generated by Django 5.2.15 on 2026-07-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_carimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspection_pending', 'Inspection Pending'), ('listing_approved', 'Listing Approved'), ('inspection_in_progress', 'Inspection In Progress'), ('needs_clearance', 'Needs Clearance'), ('inspection_rejected', 'Inspection Rejected'), ('inspection_no_show', 'Inspection No Show'), ('needs_changes', 'Needs Changes'), ('published', 'Published'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30),
        ),
    ]
