# Generated by Django 5.2.15 on 2026-07-08 04:46

from django.db import migrations, models


def remap_inspection_approved_cars(apps, schema_editor):
    """`inspection_approved` no longer exists in the new flow. Cars stranded
    in it (booking approved, awaiting physical inspection) map cleanest to
    `inspection_pending` — still booked, awaiting inspection."""
    Car = apps.get_model("listings", "Car")
    Car.objects.filter(status="inspection_approved").update(
        status="inspection_pending"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_carimage_image_type'),
    ]

    operations = [
        migrations.RunPython(remap_inspection_approved_cars, migrations.RunPython.noop),
        migrations.AddField(
            model_name='car',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inspection_pending', 'Inspection Pending'), ('listing_approved', 'Listing Approved'), ('inspection_in_progress', 'Inspection In Progress'), ('needs_clearance', 'Needs Clearance'), ('inspection_rejected', 'Inspection Rejected'), ('inspection_no_show', 'Inspection No Show'), ('needs_changes', 'Needs Changes'), ('published', 'Published'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=30),
        ),
    ]
