# Generated by Django 5.2.15 on 2026-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_car_tracking_id_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
