# Generated by Django 5.2.15 on 2026-07-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_car_rent_price_per_day_alter_car_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_negotiable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=10),
        ),
    ]
