# Generated by Django 5.2.15 on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_car_is_negotiable_car_max_price_car_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
