# Generated by Django 5.2.15 on 2026-07-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_delete_both_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='min_price',
        ),
    ]
