# Generated by Django 5.2.15 on 2026-08-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
