# Generated by Django 5.2.15 on 2026-08-01 05:21

import django.db.models.deletion
from django.db import migrations, models


def populate_brand_ref(apps, schema_editor):
    """Point each car at its canonical Brand row (matched by the already-canonical
    brand string from the Spec-4 backfill). Unmatched/blank → left null."""
    Car = apps.get_model("listings", "Car")
    Brand = apps.get_model("listings", "Brand")
    by_name = {b.name: b.id for b in Brand.objects.all()}
    lower = {b.name.lower(): b.id for b in Brand.objects.all()}
    for car in Car.objects.exclude(brand="").only("id", "brand"):
        brand_id = by_name.get(car.brand) or lower.get(car.brand.lower())
        if brand_id:
            car.brand_ref_id = brand_id
            car.save(update_fields=["brand_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_reseed_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='listings.brand'),
        ),
        migrations.RunPython(populate_brand_ref, migrations.RunPython.noop),
    ]
