# Generated by Django 5.2.15 on 2026-08-01 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_finalize_brand_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('vin__isnull', False), models.Q(('status', 'archived'), _negated=True)), fields=('vin',), name='one_active_listing_per_vin'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('plate_number__isnull', False), models.Q(('status', 'archived'), _negated=True)), fields=('plate_number',), name='one_active_listing_per_plate'),
        ),
    ]
