# Generated by Django 5.2.15 on 2026-08-06 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_car_plate_number_alter_car_vin_and_more'),
        ('users', '0013_alter_ownerprofile_id_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_branches', to='users.ownerprofile')),
            ],
            options={
                'db_table': 'business_branches',
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_branch_name_per_businesses')],
            },
        ),
    ]
