# Generated by Django 5.2.15 on 2026-08-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_branch'),
        ('users', '0013_alter_ownerprofile_id_document'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_name_per_businesses',
        ),
        migrations.AlterField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.ownerprofile'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_branch_name_per_business'),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
