# Generated by Django 5.2.15 on 2026-08-16 03:26

import django_countries.fields
from django.db import migrations


def backfill_branch_country(apps, schema_editor):
    """Existing branches were created before per-branch country existed — seed
    each with its business's registered country so nothing changes for them."""
    Branch = apps.get_model("listings", "Branch")
    for branch in Branch.objects.select_related("business").filter(country=""):
        business_country = branch.business.country
        if business_country:
            branch.country = business_country
            branch.save(update_fields=["country"])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.RunPython(
            backfill_branch_country, migrations.RunPython.noop
        ),
    ]
