# Generated by Django 5.2.15 on 2026-08-22 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_alter_requeststatusevent_actor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDeletionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('outcome', models.CharField(choices=[('sold_platform', 'Sold on EverythingCars'), ('sold_elsewhere', 'Sold elsewhere'), ('not_sold', 'Not sold / other reason')], max_length=20)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_feedback', to='listings.car')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_deletion_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
