# Generated by Django 5.2.15 on 2026-08-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_cardeletionfeedback'),
        ('sales', '0003_deal_dispute_resolution_deal_dispute_resolution_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales.deal'),
        ),
    ]
