# Generated by Django 5.2.15 on 2026-06-17 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('request_received', 'New request received'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('request_cancelled', 'Request cancelled'), ('listing_submitted', 'Listing submitted for review'), ('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing suspended'), ('listing_needs_changes', 'Listing needs changes'), ('payment_submitted', 'Payment submitted'), ('payment_confirmed', 'Payment confirmed'), ('rental_active', 'Rental is active'), ('rental_completed', 'Rental completed'), ('requests_auto_rejected', 'Requests auto-rejected'), ('system', 'System announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
