# Generated by Django 5.2.15 on 2026-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_received', 'New request received'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('request_cancelled', 'Request cancelled'), ('listing_suspended', 'Listing suspended'), ('inspection_booked', 'Inspection booked'), ('inspection_booking_approved', 'Inspection booking approved'), ('inspection_booking_rejected', 'Inspection booking rejected'), ('inspection_passed', 'Inspection passed'), ('inspection_failed', 'Inspection failed'), ('inspection_no_show', 'Inspection no-show'), ('inspection_rescheduled', 'Inspection rescheduled'), ('payment_submitted', 'Payment submitted'), ('payment_confirmed', 'Payment confirmed'), ('rental_active', 'Rental is active'), ('rental_completed', 'Rental completed'), ('requests_auto_rejected', 'Requests auto-rejected'), ('system', 'System announcement')], max_length=30),
        ),
    ]
