# Generated by Django 5.2.15 on 2026-07-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
