# Generated by Django 5.2.15 on 2026-07-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_received', 'New request received'), ('request_approved', 'Request approved'), ('request_rejected', 'Request rejected'), ('request_cancelled', 'Request cancelled'), ('listing_suspended', 'Listing suspended'), ('listing_approved', 'Listing approved'), ('listing_submitted', 'Listing submitted for review'), ('changes_requested', 'Changes requested'), ('inspection_booked', 'Inspection booked'), ('inspection_booking_approved', 'Inspection booking approved'), ('inspection_booking_rejected', 'Inspection booking rejected'), ('inspection_started', 'Inspection started'), ('needs_clearance', 'Needs further clearance'), ('clearance_response', 'Clearance response received'), ('inspection_passed', 'Inspection passed'), ('inspection_failed', 'Inspection failed'), ('inspection_no_show', 'Inspection no-show'), ('inspection_rescheduled', 'Inspection rescheduled'), ('inspection_cancelled', 'Inspection cancelled'), ('inspection_payment_submitted', 'Inspection payment submitted'), ('inspection_payment_confirmed', 'Inspection payment confirmed'), ('inspection_payment_rejected', 'Inspection payment rejected'), ('assistance_requested', 'Booking assistance requested'), ('payment_submitted', 'Payment submitted'), ('payment_confirmed', 'Payment confirmed'), ('rental_active', 'Rental is active'), ('rental_completed', 'Rental completed'), ('requests_auto_rejected', 'Requests auto-rejected'), ('offer_submitted', 'Offer submitted'), ('offer_received', 'New offer received'), ('offer_countered', 'Counter-offer received'), ('offer_accepted', 'Offer accepted'), ('offer_rejected', 'Offer declined'), ('counter_accepted', 'Counter-offer accepted'), ('counter_rejected', 'Counter-offer declined'), ('offer_expired', 'Offer expired'), ('car_no_longer_available', 'Vehicle no longer available'), ('deal_reached', 'Deal reached'), ('deal_completed', 'Deal completed'), ('deal_cancelled', 'Deal cancelled'), ('car_available_again', 'Vehicle available again'), ('deal_disputed', 'Deal completion disputed'), ('dispute_dismissed', 'Dispute dismissed — sale stands'), ('system', 'System announcement')], max_length=30),
        ),
    ]
