# Generated by Django 5.2.15 on 2026-06-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtokenblacklist_accesscode_customerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
