# Generated by Django 5.2.15 on 2026-06-05 19:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accesscode_expires_at_alter_accesscode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
