# Generated by Django 5.2.15 on 2026-06-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customerprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='drivers_liscense',
            new_name='drivers_license',
        ),
    ]
