# Generated by Django 5.2.15 on 2026-06-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_drivers_liscense_customerprofile_drivers_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='purpose',
            field=models.CharField(choices=[('sign_in', 'Sign In'), ('sign_up_verify', 'Sign Up Verify')], max_length=20),
        ),
    ]
