# Generated by Django 5.2.15 on 2026-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_accesscode_purpose'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesscode',
            index=models.Index(fields=['email', 'purpose', 'is_used', 'expires_at'], name='access_code_lookup_idx'),
        ),
    ]
