# Generated by Django 5.2.15 on 2026-06-09 02:15

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
