# Generated by Django 5.2.15 on 2026-06-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
