# Generated by Django 5.2.15 on 2026-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer_profile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity-docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('intl_passport', 'International Passport'), ('nin', 'NIN'), ('voters_card', "Voter's Card"), ('drivers_licence', "Driver's Licence")], max_length=20),
        ),
    ]
