# Generated by Django 5.2.15 on 2026-07-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_ownerprofile_id_document_ownerprofile_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='identity-docs/%Y/%m/'),
        ),
    ]
