# Generated by Django 5.2.15 on 2026-08-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('inspector', 'Inspector'), ('publisher', 'Publisher'), ('admin', 'Admin')], default='', max_length=20),
        ),
    ]
