# Generated by Django 5.2.15 on 2026-08-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_backfill_staff_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='bank_name',
        ),
    ]
