# Generated by Django 5.2.15 on 2026-07-23 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0013_delete_both_cars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('GHS', 'Ghanaian Cedi (₵)'), ('KES', 'Kenyan Shilling (KSh)'), ('ZAR', 'South African Rand (R)')], default='NGN', max_length=3)),
                ('message', models.TextField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('superseded', 'Closed — vehicle sold')], db_index=True, default='pending', max_length=20)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counter_message', models.TextField(blank=True, max_length=400)),
                ('countered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_made', to=settings.AUTH_USER_MODEL)),
                ('resulting_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_offers', to='listings.request')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['car', 'status'], name='offers_offe_car_id_e4dd7c_idx'), models.Index(fields=['customer', 'status'], name='offers_offe_custome_f151d3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'countered'])), fields=('car', 'customer'), name='one_active_offer_per_customer_per_car')],
            },
        ),
    ]
