# Generated by Django 5.2.15 on 2026-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dispute_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='deal',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
