# Generated by Django 5.2.15 on 2026-07-30 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_deal_dispute_reason_deal_disputed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dispute_resolution',
            field=models.CharField(blank=True, choices=[('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='dispute_resolution_note',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='deal',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='dispute_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
